import {
  Activity,
  Apple,
  Award,
  Banknote,
  Bell,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Calendar,
  Camera,
  Car,
  CheckCircle2,
  Cloud,
  Code2,
  Coffee,
  Coins,
  Crown,
  Dumbbell,
  Flame,
  Flower2,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Landmark,
  Leaf,
  Lightbulb,
  ListChecks,
  Medal,
  Moon,
  Music,
  Palette,
  PartyPopper,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Repeat,
  Rocket,
  Scissors,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Store,
  Sun,
  Target,
  TreePine,
  TrendingUp,
  Trophy,
  Users,
  Utensils,
  Wallet,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: 'target', icon: Target },
  { name: 'flame', icon: Flame },
  { name: 'dumbbell', icon: Dumbbell },
  { name: 'heart', icon: Heart },
  { name: 'brain', icon: Brain },
  { name: 'apple', icon: Apple },
  { name: 'leaf', icon: Leaf },
  { name: 'sun', icon: Sun },
  { name: 'moon', icon: Moon },
  { name: 'cloud', icon: Cloud },
  { name: 'code', icon: Code2 },
  { name: 'cleaning', icon: Brush },
  { name: 'coffee', icon: Coffee },
  { name: 'book', icon: BookOpen },
  { name: 'briefcase', icon: Briefcase },
  { name: 'home', icon: Home },
  { name: 'activity', icon: Activity },
  { name: 'pill', icon: Pill },
  { name: 'utensils', icon: Utensils },
  { name: 'camera', icon: Camera },
  { name: 'music', icon: Music },
  { name: 'palette', icon: Palette },
  { name: 'gamepad', icon: Gamepad2 },
  { name: 'gift', icon: Gift },
  { name: 'trophy', icon: Trophy },
  { name: 'award', icon: Award },
  { name: 'medal', icon: Medal },
  { name: 'crown', icon: Crown },
  { name: 'star', icon: Star },
  { name: 'sparkles', icon: Sparkles },
  { name: 'party', icon: PartyPopper },
  { name: 'smile', icon: Smile },
  { name: 'zap', icon: Zap },
  { name: 'calendar', icon: Calendar },
  { name: 'bell', icon: Bell },
  { name: 'wallet', icon: Wallet },
  { name: 'banknote', icon: Banknote },
  { name: 'landmark', icon: Landmark },
  { name: 'coins', icon: Coins },
  { name: 'piggybank', icon: PiggyBank },
  { name: 'trending', icon: TrendingUp },
  { name: 'shop', icon: ShoppingBag },
  { name: 'store', icon: Store },
  { name: 'car', icon: Car },
  { name: 'plane', icon: Plane },
  { name: 'bike', icon: Bike },
  { name: 'users', icon: Users },
  { name: 'flower', icon: Flower2 },
  { name: 'tree', icon: TreePine },
  { name: 'graduation', icon: GraduationCap },
  { name: 'lightbulb', icon: Lightbulb },
  { name: 'rocket', icon: Rocket },
  { name: 'phone', icon: Phone },
  { name: 'scissors', icon: Scissors },
  { name: 'check', icon: CheckCircle2 },
  { name: 'repeat', icon: Repeat },
  { name: 'list', icon: ListChecks },
];

const iconMap = Object.fromEntries(ICON_OPTIONS.map((o) => [o.name, o.icon]));

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Target;
}

export const COLOR_OPTIONS = [
  '#ffffff',
  '#f5f5f5',
  '#e5e5e5',
  '#a3a3a3',
  '#525252',
  '#262626',
  '#171717',
  '#000000',
  '#6366f1',
  '#8b5cf6',
  '#7c3aed',
  '#9333ea',
  '#a855f7',
  '#ec4899',
  '#e11d48',
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#ca8a04',
  '#a3e635',
  '#84cc16',
  '#65a30d',
  '#4ade80',
  '#22c55e',
  '#16a34a',
  '#15803d',
  '#10b981',
  '#059669',
  '#047857',
  '#14b8a6',
  '#0d9488',
  '#06b6d4',
  '#0891b2',
  '#3b82f6',
  '#2563eb',
  '#64748b',
];

export const DEFAULT_KIND_ICON: Record<string, string> = {
  income: 'banknote',
  expense: 'shop',
  transfer: 'wallet',
  fixed_cost: 'calendar',
  buy_apply: 'shop',
  buy_planned: 'shop',
  adjustment: 'target',
  forecast: 'trending',
};

export const DEFAULT_KIND_COLOR: Record<string, string> = {
  income: '#10b981',
  expense: '#ec4899',
  transfer: '#6366f1',
  fixed_cost: '#8b5cf6',
  buy_apply: '#ec4899',
  buy_planned: '#ec4899',
  adjustment: '#64748b',
  forecast: '#3b82f6',
};
