import {
  Activity,
  Apple,
  Baby,
  BadgePercent,
  Banknote,
  Bell,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Camera,
  Car,
  CheckCircle2,
  Cloud,
  Code2,
  Coffee,
  CreditCard,
  Dog,
  Droplets,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Landmark,
  Leaf,
  Lightbulb,
  ListChecks,
  MapPin,
  Moon,
  Music,
  Palette,
  PartyPopper,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Plug,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Store,
  Sun,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Umbrella,
  Utensils,
  Watch,
  Waves,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { BeerIcon, CigaretteIcon, GrillIcon, TentIcon } from './customIcons';

export const ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  // Health & fitness
  { name: 'dumbbell', icon: Dumbbell },
  { name: 'heart', icon: Heart },
  { name: 'apple', icon: Apple },
  { name: 'activity', icon: Activity },
  { name: 'pill', icon: Pill },
  { name: 'baby', icon: Baby },
  // Food & drink
  { name: 'utensils', icon: Utensils },
  { name: 'coffee', icon: Coffee },
  { name: 'beer', icon: BeerIcon },
  { name: 'cigarette', icon: CigaretteIcon },
  { name: 'grill', icon: GrillIcon },
  // Home & shopping
  { name: 'home', icon: Home },
  { name: 'shop', icon: ShoppingBag },
  { name: 'store', icon: Store },
  { name: 'cart', icon: ShoppingCart },
  { name: 'shirt', icon: Shirt },
  // Transport
  { name: 'car', icon: Car },
  { name: 'plane', icon: Plane },
  { name: 'bike', icon: Bike },
  { name: 'bus', icon: Bus },
  { name: 'train', icon: TrainFront },
  { name: 'fuel', icon: Fuel },
  { name: 'ticket', icon: Ticket },
  { name: 'tent', icon: TentIcon },
  // Nature & weather
  { name: 'leaf', icon: Leaf },
  { name: 'sun', icon: Sun },
  { name: 'moon', icon: Moon },
  { name: 'cloud', icon: Cloud },
  { name: 'wave', icon: Waves },
  { name: 'umbrella', icon: Umbrella },
  // Finance
  { name: 'banknote', icon: Banknote },
  { name: 'landmark', icon: Landmark },
  { name: 'piggybank', icon: PiggyBank },
  { name: 'trending', icon: TrendingUp },
  { name: 'calendar', icon: Calendar },
  { name: 'credit', icon: CreditCard },
  { name: 'percent', icon: BadgePercent },
  // Work & education
  { name: 'briefcase', icon: Briefcase },
  { name: 'graduation', icon: GraduationCap },
  { name: 'code', icon: Code2 },
  { name: 'lightbulb', icon: Lightbulb },
  { name: 'phone', icon: Phone },
  { name: 'wrench', icon: Wrench },
  // Leisure
  { name: 'gamepad', icon: Gamepad2 },
  { name: 'music', icon: Music },
  { name: 'camera', icon: Camera },
  { name: 'palette', icon: Palette },
  { name: 'book', icon: BookOpen },
  { name: 'gift', icon: Gift },
  { name: 'party', icon: PartyPopper },
  { name: 'tv', icon: Tv },
  { name: 'headphones', icon: Headphones },
  { name: 'watch', icon: Watch },
  { name: 'map', icon: MapPin },
  // Utilities & pets
  { name: 'bell', icon: Bell },
  { name: 'zap', icon: Zap },
  { name: 'wifi', icon: Wifi },
  { name: 'plug', icon: Plug },
  { name: 'water', icon: Droplets },
  { name: 'dog', icon: Dog },
  { name: 'scissors', icon: Scissors },
  { name: 'check', icon: CheckCircle2 },
  { name: 'repeat', icon: Repeat },
  { name: 'list', icon: ListChecks },
];

const iconMap = Object.fromEntries(ICON_OPTIONS.map((o) => [o.name, o.icon]));

/** Icons removed from the picker; map to a sensible replacement when loading stored data. */
export const DEPRECATED_ICON_ALIASES: Record<string, string> = {
  flame: 'zap',
  brain: 'lightbulb',
  cleaning: 'home',
  award: 'party',
  medal: 'party',
  crown: 'party',
  trophy: 'party',
  star: 'repeat',
  target: 'repeat',
  sparkles: 'party',
  smile: 'party',
  wallet: 'credit',
  coins: 'banknote',
  users: 'repeat',
  flower: 'leaf',
  tree: 'leaf',
  rocket: 'repeat',
};

export function resolveIconName(name: string | null | undefined): string {
  if (!name) return 'repeat';
  if (iconMap[name]) return name;
  return DEPRECATED_ICON_ALIASES[name] ?? 'repeat';
}

export function getIcon(name: string): LucideIcon {
  return iconMap[resolveIconName(name)] ?? Repeat;
}

/** One row of balanced hues; fewer neutrals than before. */
export const COLOR_OPTIONS = [
  '#ffffff',
  '#e5e5e5',
  '#737373',
  '#171717',
  '#6366f1',
  '#7c3aed',
  '#9333ea',
  '#c026d3',
  '#ec4899',
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#eab308',
  '#84cc16',
  '#22c55e',
  '#10b981',
  '#14b8a6',
  '#06b6d4',
  '#3b82f6',
  '#64748b',
];

export const DEFAULT_KIND_ICON: Record<string, string> = {
  income: 'banknote',
  expense: 'shop',
  transfer: 'repeat',
  fixed_cost: 'calendar',
  buy_apply: 'shop',
  buy_planned: 'shop',
  adjustment: 'list',
  forecast: 'trending',
  income_forecast: 'banknote',
  expense_forecast: 'calendar',
  stock_purchase: 'trending',
  stock_sale: 'trending',
};

export const DEFAULT_KIND_COLOR: Record<string, string> = {
  income: '#10b981',
  expense: '#ec4899',
  transfer: '#6366f1',
  fixed_cost: '#8b5cf6',
  buy_apply: '#ec4899',
  buy_planned: '#ec4899',
  adjustment: '#64748b',
  forecast: '#3b82f6',
  income_forecast: '#10b981',
  expense_forecast: '#8b5cf6',
  stock_purchase: '#f59e0b',
  stock_sale: '#10b981',
};
